service: email-api-python

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  environment:
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    EMAIL_HOST: ${env:EMAIL_HOST, 'smtp.gmail.com'}
    EMAIL_PORT: ${env:EMAIL_PORT, '587'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true
    timeout: 30

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0

package:
  exclude:
    - node_modules/**
    - .env
    - __pycache__/**
    - .pytest_cache/**
    - tests/**
